Add Sign in form validation
profolio-team/customer-admin pull request #122
Opened 2022-05-28 10:15 UTC by Isca7el

Add hookform resolvers for validation form(package.json). Add regular exprassion to formValidator. Add validation to SignIn.

2022-05-28 11:11 UTC, dmowski requested changes
нужно обновить ветку. есть гит конфликты

2022-05-28 11:11 UTC, dmowski commented on app/src/components/AuthForms/SignIn/SignIn.tsx
> +            type="text"
лучше оставить тип email.
потому-что это поле явно является email

2022-05-28 15:20 UTC, Isca7el commented on app/src/components/AuthForms/SignIn/SignIn.tsx
> +            type="text"
Если type="email", когда просто нажимаешь на поле то появляется диалоговое окно, для email вылетает окно "Адрес электронной должен содержать @", пробовал избавитьс от него с помощью eventPreventDefault, не получилось, потому сделал такой вариант.

2022-05-28 17:11 UTC, dmowski commented on app/src/components/AuthForms/SignIn/SignIn.tsx
> +            type="text"
"когда просто нажимаешь на поле то появляется диалоговое окно"
Можешь скинуть скрин этого окна?

2022-05-28 17:24 UTC, Isca7el commented on app/src/components/AuthForms/SignIn/SignIn.tsx
> +            type="text"
Например вводишь свой логин без домена @, и нажимаешь на кнопку Continue вылетает такое окно
![err](https://user-images.githubusercontent.com/77880315/170836141-deab3be6-d5d5-4b02-b2fc-058fe953f261.png)

2022-05-28 20:10 UTC, dmowski commented on app/src/components/AuthForms/SignIn/SignIn.tsx
> +            type="text"
так и нужно. это нативная валидация браузера.

2022-05-28 20:15 UTC, dmowski commented on app/src/components/AuthForms/SignIn/SignIn.tsx
> +            type="text"
и навер правильнее сказать что это не диалоговое окно.. это скорее браузерный тултип.. или ещё можно сказать подсказка

2022-06-03 05:45 UTC, closed without merging

2022-06-03 05:45 UTC, Isca7el commented
Not right solution