Add InputValidator
profolio-team/customer-admin pull request #130
Opened 2022-06-02 21:00 UTC by Anton-Shvetc

Добавлен компонент InputValidator 
Для тестирования временно подвязан на db.users

2022-06-04 20:57 UTC, dmowski requested changes

2022-06-04 20:57 UTC, dmowski commented on app/src/components/InputValidator/InputValidator.tsx
> +  async function CheckDbMatch(area: string, inputValue: string) {
```js

async function validateInput(inputValue: string) {
    const validateResult = await props.validator(inputValue)

    if (validateResult.error) {
      setErrosMessage(validateResult.errorMessage || 'Input value invalid');
    }

    return;
  }
```
функцию props.validator передаешь в этот компонент через пропсы
validator - это функция которая валидирует строку. (делает запросы.. все что угодно)
главное условие, что это функция асинхронная и это функция возвращает результат валидации... ок или не ок.
в моем примере она возвращает обьект {error: boolean, errorMessage?: string} (но это чисто пример)

------

С таким подходом этот компонент становиться универсальным.
А бизнес логика по определению валидности строки перенесится на то место где создаешь компонент.

Для примера как это может выглядить извне

```js
const newUserValidator = async (username:string) => {
    const userQuery = query(db.users, where('firstName', "==", username));
    const userSnapshot = await getDocs(userQuery);
    if (userSnapshot.docs.length > 0) {
        return {
                error: true,
                errorMessage: "User already exists"
        }
    } else {
        return {
                error: false
        }        
    }
}

<InputValidator validator={newUserValidator} value={firstName} onChange={(e)=>setFirstName(e.target.value)} />


```

2022-06-04 20:57 UTC, dmowski commented on app/src/components/InputValidator/InputValidator.tsx
> +      onBlur={(e) => {
я бы советовал делать что-то вроде
onBlur={(e) => {
    if (validator(e.target.value)) {
      props.onBlur(e)
    }
}}

и тоже самое для onChange.. чтобы была возможность извне подписаться на эти события

2022-06-05 09:22 UTC, Isca7el commented on app/src/components/InputValidator/InputValidator.tsx
> +  async function CheckDbMatch(area: string, inputValue: string) {
Я использовал yupResolver, для него делал schemaValidation (schemaEmail, schemaPassword). Они выполняют те же функции. Можно прописать для всех наших валидаций в одном файле, и экспортировать в нужное место.

2022-06-13 12:13 UTC, closed without merging