temp commit
profolio-team/customer-admin pull request #159
Opened 2022-06-20 19:16 UTC by dllsc

## Описание 📝

Делаю страницу с таблицей пользователя

На данном этапе хочу показать солюшн фильтрации (фитча еще не готова)

Страница еще в разработке

---

### На что стоит обратить внимание при ревью 👀

Драфтовый пулл реквест, что бы понять правильное ли направлении.

Стоит обратить внимание на автокомлиты, особенно на автокомлит поиска пользователей (вынес отдельным компоненом)
В будущем сделаю его контролируемым компонентом под реакт хук форм.
Или использую провайдер для формы.

---

### Скриншоты экранов если нужны 📺 🖥

![image](https://user-images.githubusercontent.com/92045376/174665628-95124927-7ac3-4591-a9be-51d7ecce7c89.png)

2022-06-20 19:23 UTC, dmowski requested changes

2022-06-20 19:23 UTC, dmowski commented on app/src/components/AutocompleteName.tsx
> +        orderBy('firstName'),
сто про в продакшене это не будет работать.
Почитай про индексы фаербэйса

2022-06-20 19:23 UTC, dmowski commented on app/src/components/AutocompleteName.tsx
> +                where('lastName', '<=', `${lastName}~`),
если это прототим, удоляй

2022-06-20 19:23 UTC, dmowski commented on app/src/components/AutocompleteName.tsx
> +                where('lastName', '<=', `${lastName}~`),
что за дикие запросы

2022-06-20 19:23 UTC, dmowski commented on app/src/views/Users/UsersPage.tsx
> +interface FilteringFields {
что за фильтр? почему такое название*

2022-07-08 13:47 UTC, dmowski commented on typescript-types/db.types.ts
> +  headId: string;
У нас по умолчанию будет head? как это будет работать?

2022-07-08 13:48 UTC, dmowski commented on app/src/components/AutocompleteLocation.tsx
> +  const [q, setQ] = useState(
не называй переменный одной буквой

2022-07-08 14:01 UTC, dmowski approved these changes

2022-07-08 14:41 UTC, dllsc commented on typescript-types/db.types.ts
> +  headId: string;
пустой строкой

2022-07-09 07:52 UTC, dllsc commented on app/src/components/AutocompleteLocation.tsx
> +  const [q, setQ] = useState(
fix

2022-07-09 08:18 UTC, merged