UI component: Block with carts of company portfolio
profolio-team/customer-admin pull request #230
Opened 2022-09-16 11:07 UTC by roman-samsonick

Work done:

*Add CompanyPortfolioPage
*Add navigation by cards by keyboard
*Add possibility to transfer data by props

2022-09-16 11:20 UTC, dmowski commented on app/src/components/CompanyPortfolio/Banner.tsx
> +const CompanyDescription = styled.div`
мы используем другой подход в создании стилевых компонентов (без шаблонов)

styled.div({
height: "36px;"

2022-09-16 11:21 UTC, dmowski commented on app/src/AppRouter.tsx
> +      <Route path="/company-portfolio" element={<CompanyPortfolioPageWrapper />} />
ненужно его добавлять в проект. Добавь пока только в сторибуки

2022-09-16 11:21 UTC, dmowski commented on app/src/hooks/useAuth.tsx
> +    "/company-portfolio",
тут тоже не нужно

2022-09-16 11:31 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +    <CardContainer className={classes} ref={myRef}>
просто Card

2022-09-16 11:31 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +      <CardContentContainer>
<Content>

2022-09-16 11:33 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +      setSelectedY(boundValue(selectedY + 1, 0, 4));
для чего эта логика?

2022-09-16 11:34 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +                    x={x}
что значит x?

2022-09-16 11:40 UTC, dmowski commented
Изображения положить в папку assets

2022-09-16 11:41 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +function scrollIntoViewIfNeeded(target: HTMLElement) {
зачем эта функция?

2022-09-16 11:44 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +const CardsContainer = styled.div`
Добавь в этот тэг атрибут или класс. dark.
```
.dark & {
    --color-neutral-1: var(--dark-color-neutral-1)
}
```

Суть в том чтобы в родительском компоненте изменить css переменные.
Сделать их темными. И так у тебя получится темная тема.

2022-09-16 11:53 UTC, dmowski commented on app/src/components/CompanyPortfolio/CompanyPortfolioPage.tsx
> +export const CompanyMockData: ICompanyPortfolio = {
перенеси данные в отдельный модуль. Например
app/src/components/CompanyPortfolio/MockData.tsx

2022-09-16 11:55 UTC, dmowski commented on app/src/components/CompanyPortfolio/CompanyPortfolioPage.tsx
> +export const PortfolioPage = styled.div`
перенести в файл со стилями

2022-09-16 11:56 UTC, dmowski commented on app/src/components/CompanyPortfolio/CompanyPortfolioPage.tsx
> +export const CompanyMockData: ICompanyPortfolio = {
не используем префикс I
лучше сделать CompanyPortfolioInfo

2022-09-16 11:56 UTC, dmowski commented on app/src/components/CompanyPortfolio/CompanyPortfolioPage.tsx
> +export const CompanyPortfolioPage = ({ font, theming, data }: ICompanyPortfolioPageProps) => {
* CompanyPortfolioPageProps

2022-09-16 12:08 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +              {cardRow.map((item, x) => {
для чего нужно разбиение на row.
Можно просто выводить карточки попорядку.
<CardsContainer>
<Card *** >
<Card *** >
<Card *** >
<Card *** >
<Card *** >
</CardsContainer>

2022-09-16 13:02 UTC, roman-samsonick commented on app/src/components/CompanyPortfolio/Cards.tsx
> +      setSelectedY(boundValue(selectedY + 1, 0, 4));
Для того, чтобы по карточкам можно было навигировать через клавиатуру

2022-09-16 13:09 UTC, roman-samsonick commented on app/src/components/CompanyPortfolio/Cards.tsx
> +                    x={x}
X - положение элемента по оси x(горизантально(← →))

2022-09-16 13:14 UTC, JohnSutray commented on app/src/components/CompanyPortfolio/Cards.tsx
> +function scrollIntoViewIfNeeded(target: HTMLElement) {
Полагаю, для того, чтобы отскроллить к элементу, если это необходимо =)

2022-09-16 13:18 UTC, roman-samsonick commented on app/src/components/CompanyPortfolio/Cards.tsx
> +function scrollIntoViewIfNeeded(target: HTMLElement) {
Для того, чтобы отскроллить к элементу, если это необходимо =)

2022-09-16 13:19 UTC, dllsc commented on app/src/components/CompanyPortfolio/Cards.tsx
> +function scrollIntoViewIfNeeded(target: HTMLElement) {
Я почти уверен, что это нужно для того, чтобы отскроллить к элементу, если это необходимо =)

2022-09-16 13:27 UTC, roman-samsonick commented on app/src/components/CompanyPortfolio/Cards.tsx
> +    <CardContainer className={classes} ref={myRef}>
Тег Card уже занят =)

2022-09-16 19:49 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +      setSelectedY(boundValue(selectedY + 1, 0, 4));
это делается с помощью псевдо селектора :focus-within
-------

https://ru.ariarzer.dev/tutorials/2022/easy-semantic-card-link.html

https://codepen.io/dmowski/pen/OJZppoY

2022-09-16 19:49 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +                    x={x}
окей. это делается без js. 

Только css,html

2022-09-16 19:50 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +function scrollIntoViewIfNeeded(target: HTMLElement) {
Зачем это нам нужно?

2022-09-16 19:54 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +function scrollIntoViewIfNeeded(target: HTMLElement) {
просматривая кода и используя тактику 5 почему, ты можешь быстро отследить ключевые моменты где можно улучшить свой код

2022-09-16 19:58 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +              {cardRow.map((item, x) => {
используй верстку с помощью css grid

2022-09-16 19:59 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +    <CardContainer className={classes} ref={myRef}>
может тогда использовать лучше ProfolioCard

2022-09-16 20:05 UTC, dmowski commented on app/src/components/CompanyPortfolio/Cards.tsx
> +function scrollIntoViewIfNeeded(target: HTMLElement) {
енто што был тролинг??))
<img width="447" alt="image" src="https://user-images.githubusercontent.com/17089422/190724200-310ae656-f4d8-4085-9884-14f61e61fd5b.png">

2022-10-03 18:50 UTC, dmowski requested changes
fsdsdf

2022-10-03 18:51 UTC, dmowski commented on app/src/components/CompanyPortfolio/Banner.tsx
> +const CompanyDescription = styled.div`
fixed

2022-10-21 19:48 UTC, closed without merging