UI component: Card block of company portfolio
profolio-team/customer-admin pull request #234
Opened 2022-09-22 16:04 UTC by roman-samsonick

Work done:

*Add Company portfolio card
*Add it to storybook
*Add some global styles of dark theme

2022-09-22 18:16 UTC, dmowski commented on app/src/stories/CompantPortfolioCard.stories.tsx
> +  const MockData = {
portfolioCardMockData

2022-09-22 18:17 UTC, dmowski commented on app/src/stories/CompantPortfolioCard.stories.tsx
> +  title: "Components/CompanysPortfolio",
CompanyPortfolio (опечатка)
установи Code Spell Checker

2022-09-22 18:19 UTC, dmowski commented
Этой белой рамки быть не должно. не оч красиво выглядит
<img width="438" alt="image" src="https://user-images.githubusercontent.com/17089422/191822192-4cadc2ee-1c2d-4cb2-b26a-b8f62bde955d.png">

2022-09-22 18:20 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +export const Card = styled.div({
Вынести стили в файл стилей компонента

2022-09-22 18:41 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +  height: "620px",
высоту/ширину лучше указать не захардкоженную.

width: 100%
height: 100% или auto или max-content

но в любом случае не хардкоды. потому-что с ними будет сложно делать адаптивность.

Лучше чтобы ширину карточки задавал контейнер

2022-09-22 18:42 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +  backgroundColor: "var(--background-color-1)",
вижу что по дизайну фон по умолчанию прозрачный. 
думаю так его и оставить
<img width="934" alt="image" src="https://user-images.githubusercontent.com/17089422/191826370-70a42d55-65fa-4382-b1ca-c5bd570c73ec.png">

т.е. или backgroundColor: 'transparent' или вообще не указывать это свойство по умолчанию

2022-09-22 18:46 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +        <CardTheme>{data.theme}</CardTheme>
по макетам тут хранится не название темы.
![image](https://user-images.githubusercontent.com/17089422/191826926-811035b4-a1c4-4b5d-be56-038569408254.png)

я бы назвал этот элемент категория
<Category>{data.category}<Category>

2022-09-22 18:48 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +  font: string;
думаю сдесь лучше жестачэйше ограничить API этого компонента.
font: 'sans' | 'sans-serif';

2022-09-22 18:55 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +export interface PortfolioCardInterface {
я бы сделал такую композицию пропертей


interface PortfolioCardData {
  title: string;
  description: string;
  category: string;
  tags: string[];
  id: number;
  imageSrc: string;
  href: string; //карточка должна при клике переводить на другиую страницу
}

interface PortfolioCardStyle {
  theme: 'dark' | 'white';
  font: 'sans' | 'sans-serif';
}

interface PortfolioCardProps {
  data: PortfolioCardData;
  style: PortfolioCardStyle;
}

2022-09-22 19:07 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +    <Card className={theme} style={{ fontFamily: font }}>
а тут можно сделать так

```
export const PortfolioCard = ({ data, style }: PortfolioCardProps) => {
  return (
    <Card theme={style.theme} font={style.font}>
```



```
export const Card = styled.div<{ font: "sans" | "sans-serif"; theme: "dark" | "light" }>(
  ({ font, theme }) => ({
    fontFamily: font === "sans" ? "var(--font-sans)" : "var(--font-sans-serif)",
    "--profolio-card-color1": theme == "dark" ? "var(--color-neutral-1)" : "var(--color-negative-1)",
    "--profolio-card-color2": theme == "dark" ? "var(--color-neutral-2)" : "var(--color-negative-3)",
    "--profolio-category-gradient": theme == "dark" ? "var(--light-gradient)" : "var(--light-gradient)",

    "&:hover ": {
      backgroundColor: "var(--profolio-card-color1)",
    },
  })
);
```

т.е. прикол в том что в компоненте Card ты создаешь css переменные в зависимости от проперти theme.

И уже в других дочерних компонентах ты юзаешь эти css проперти вообще не задумываясь про темизацию.

например твой CardTheme (которые будет CardCategory)
будет примерно таким
```
const CardTheme = styled.div({
  display: "inline",
  borderRadius: "16px",
  padding: "4px 20px",
  background: "var(--profolio-category-gradient)",
});
```

2022-09-22 19:12 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +  display: "-webkit-box",
нужно придумать подход без специфичный префиксов для вебкита. 
Это ведет к багам в разных браузерах.

Подход должен быть общим.
Потому что с такими хаками будут ситуации что в каком нибуть браузере (название которого заканчивается на аерфокс, или афари:) компонент будет отображаться не так как хотелось бы

2022-09-22 19:13 UTC, dmowski commented
при клике на карточку должен быть переход на другую страницу. Мож сделать это через тэг `<a href>`

2022-09-27 16:27 UTC, dmowski commented on app/src/stories/CompantPortfolioCard.stories.tsx
> +
перенеси файл  app/src/stories/CompantPortfolioCard.stories.tsx в папку
app/src/components/CompanyPortfolio

2022-09-27 16:28 UTC, dmowski commented on app/src/components/CompanyPortfolio/style.tsx
> +  width: "488px",
без хардкодных пикселей

2022-09-27 16:28 UTC, dmowski commented on app/src/components/CompanyPortfolio/style.tsx
> +  width: "488px",
без хардкодных пикселей

2022-09-27 16:28 UTC, dmowski commented on app/src/components/CompanyPortfolio/style.tsx
> +  maxWidth: "488px",
хардкоды. нужно переписать на относительные еденицы

2022-09-27 16:32 UTC, dmowski commented on app/src/assets/styles/globals.css
> +  --profolio-card-background-color-1: #272b30;
--profolio-card-background-color-1: var(--color-neutral-9)

2022-09-27 16:33 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +      href="http://localhost:6006/?path=/story/error-pages--unexpected-error"
значение должно приходить их параметров

2022-09-27 16:35 UTC, dmowski commented on app/src/components/CompanyPortfolio/style.tsx
> +  display: "-webkit-box",
нужно придумать подход без браузерных префиксов

2022-09-27 16:35 UTC, dmowski commented on app/src/components/CompanyPortfolio/style.tsx
> +  display: "-webkit-box",
нужно придумать подход без браузерных префиксов

2022-09-27 16:37 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +        textDecoration: "none",
вынеси в файл стилей

2022-09-27 16:45 UTC, dmowski commented on app/src/stories/CompantPortfolioCard.stories.tsx
> +        fontFamily: font,
кста класное решение с классом .dark 🔥

Я наверное думаю что такуюже штуку можно сделать и со шрифтами.

Потому что сейчас у тебя применяются дефолтные браузерные шрифты.
и они не оч красивые. Лучше сделать например класс

--sans-serif-font: 'CustomSansSerifFont', 'Georgia', 'TimesNewRoman', 'sans-serif';
--sans-font: 'CustomSansSerifFont', 'Georgia', 'TimesNewRoman', 'sans-serif';
fontFamily: var(--sans-font);

.sans-serif-font {
    fontFamily: var(--sans-serif-font);
}

.sans-font {
    fontFamily: var(--sans-font);
}


так будет намного гибче

2022-09-27 16:47 UTC, dmowski commented on app/src/stories/CompantPortfolioCard.stories.tsx
> +        height: "1000px",
и задай более мене похожий на реальный контейнер.
например с гридом.
gridTemplateColumns:'1fr 1fr',

2022-09-27 16:48 UTC, dmowski requested changes
оставил комменты. В целом идет неплохо. 
Найс 🔥

2022-09-30 17:46 UTC, Anton13602 commented on app/src/stories/CompantPortfolioCard.stories.tsx
> +        height: "1000px",
сделал gridTemplateColumns:'1fr 1fr',

2022-09-30 17:46 UTC, Anton13602 commented on app/src/stories/CompantPortfolioCard.stories.tsx
> +        fontFamily: font,
исправил

2022-09-30 17:47 UTC, Anton13602 commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +        textDecoration: "none",
вынес в файл стилей 'LinkCard'

2022-09-30 17:48 UTC, Anton13602 commented on app/src/components/CompanyPortfolio/style.tsx
> +  display: "-webkit-box",
сделал метод fixContent, который зависит от длины строки

2022-09-30 20:15 UTC, dmowski commented on app/src/assets/styles/globals.css
> +  --sans-serif-font: "CustomSansSerifFont", "Georgia", "TimesNewRoman", "sans-serif";
CustomSansSerifFont was an example. please use real name of font.
And include this font. Try to load font from google fonts service 

<img width="675" alt="image" src="https://user-images.githubusercontent.com/17089422/193349441-e40b252d-65bd-4c13-94cc-83535fae8ed6.png">

2022-09-30 20:17 UTC, dmowski commented on app/src/assets/styles/globals.css
> +}
:root{
***
--profolio-card-background-color-1: ****
--profolio-card-category: ****
--profolio-card-background-color-2: #e8f4ff;
}

dark {
  --color-neutral-10: var(--color-neutral-1);
  --color-neutral-8: var(--color-neutral-5);
  --profolio-card-background-color-1: var(--color-neutral-9);
  --profolio-card-background-color-2: #32404f;
  --profolio-card-category: linear-gradient(95.93deg, #4f688d 0%, #284572 100%);
}

2022-09-30 20:50 UTC, dmowski requested changes

2022-09-30 20:50 UTC, dmowski commented on app/src/components/CompanyPortfolio/style.tsx
> +  maxWidth: "520px",
focus state looks weird.
you can remove maxWidth for make card fill container

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/17089422/193350490-e6d8d330-e03d-4301-9d3f-5756ebad1413.png">

2022-09-30 20:50 UTC, dmowski commented on app/src/components/CompanyPortfolio/style.tsx
> +export const LinkCard = styled.a({
```
export const LinkCard = styled.a({
  textDecoration: "none",
  ">div:hover, &:focus": {
    backgroundColor: "var(--profolio-card-background-color-2)",
    img: {
      scale: "1.1",
    },
  },
  "&:focus": {
    outline: "2px solid var(--color-theme-primary)",
    borderRadius: "16px",
  },
});
```

2022-09-30 20:50 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +  const fixContent = (text: string, counter: number): string => {
I would name it sliceString. 
and remove maxHeight from CardTitle.

i would say that okay if sometime user will see 3 line of text.
any way we have trimmed title by JS

2022-09-30 20:50 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +  const fixContent = (text: string, counter: number): string => {
you can move this function from PortfolioCard
its unnecessary to re-create function on each render

2022-09-30 20:50 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +    <LinkCard href={data.link}>
please make template flat
```
    <LinkCard href={data.link}>
      <Card>
        <WrapperImage className={"image-container"}>
          <Image src={data.imageSrc} />
        </WrapperImage>

        <CardCategory>{data.category}</CardCategory>

        <CardTitle>{sliceString(data.title, maxCountSymbolForTitle)}</CardTitle>

        <CardDescription>
          {sliceString(data.description, maxCountSymbolForDescription)}
        </CardDescription>

        <Tags>
          {data.tags.map((tag, i) => {
            return <Tag key={i}>{tag}</Tag>;
          })}
        </Tags>
      </Card>
    </LinkCard>
```

2022-10-01 12:29 UTC, Anton13602 commented on app/src/components/CompanyPortfolio/style.tsx
> +export const LinkCard = styled.a({
scale: "1.1" не совсем верно. Т.к. по макту убираются отступы слева и справа.

2022-10-01 12:30 UTC, Anton13602 commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +  const fixContent = (text: string, counter: number): string => {
удалил maxHeight

2022-10-01 12:30 UTC, Anton13602 commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +  const fixContent = (text: string, counter: number): string => {
Вынес функцию

2022-10-01 12:36 UTC, Anton13602 commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +    <LinkCard href={data.link}>
оставил контейнер для контента, чтобы не добавлять в каждый класс padding.

2022-10-01 20:37 UTC, dmowski commented on app/src/components/CompanyPortfolio/CompantPortfolioCard.stories.tsx
> +import { portfolioCardMockData } from "../../data/messages/CompantPortfolioCardData";
Company

опечатка

2022-10-01 20:37 UTC, dmowski commented on app/src/components/CompanyPortfolio/CompantPortfolioCard.stories.tsx
> +    <div
добавь несколько карточек для наглядности
    <div
      className={`${theme + " " + font}`}
      style={{
        backgroundColor: "var(--profolio-card-background-color-1)",
        display: "grid",
        gap: "20px",
        gridTemplateColumns: "1fr 1fr",
      }}
    >
      <PortfolioCard data={portfolioCardMockData} />
      <PortfolioCard data={portfolioCardMockData} />
      <PortfolioCard data={portfolioCardMockData} />
      <PortfolioCard data={portfolioCardMockData} />
    </div>

2022-10-01 20:41 UTC, dmowski commented on app/src/components/CompanyPortfolio/PortfolioCard.tsx
> +        <CardContentContainer>
рассинхрон именований
или сделай
ImageWrapper и CardСontentWrapper
или
ImageСontainer и CardСontentСontainer

2022-10-01 20:41 UTC, dmowski commented on app/src/components/CompanyPortfolio/style.tsx
> +  maxWidth: "520px",
Актуально

2022-10-02 10:19 UTC, dmowski approved these changes

2022-10-02 10:20 UTC, merged