create preview content component
profolio-team/customer-admin pull request #332
Opened 2023-01-22 10:25 UTC by MishaMgla

Компонент контента превью шоукейса, который будет находиться в модальном окне превью шоукейса. Только начало - хедер и основная информация. Добавил в тип шоукейса и мок данные категории.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/98478673/213911033-890a2a99-8e23-4c62-b547-6054c80d321e.png">

---

### На что стоит обратить внимание при ревью 👀

Может быть это драфтовый пулл реквест, что бы понять правильное ли направлении.

Например "Сделал пример стилизации компонента, не уверен что в правильном направлении иду, гляньте плез. Нужен общий ревью. не влезая в детали"
то в этом блоке стоит описать это. Что не нужно придираться к мелочам, что пока норм если есть логи и коментарии.

Если это готовый пулл реквест, то это тоже лучше описать тут.

"ПР полностью готов к финальному ревью. Нужно проверить всё"

---

### Скриншоты экранов если нужны 📺 🖥

Пару скриншотов помогут легче вникнуть в проект и код ревью пройдет быстрее

---

### Чеклист проверки ✅

- [ ] Проверил в мобильной версии
- [ ] Проверил в Firefox
- [ ] Изображения оптимизированы
- [ ] Компоненты в сторибуке не сломались
- [ ] Readme актуальный
- [ ] database-structure.txt актуальный

2023-01-22 10:36 UTC, dmowski commented on app/src/assets/styles/globals.css
> +  --color-neutral-7: #fff;
это действительно такие значения из фигмы? 9, 7, 10 - идентичны.

2023-01-22 10:37 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/PreviewContent.tsx
> +            {data.roles
data.roles?.[0].name

2023-01-22 10:38 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +type PreviewHeaderProps = {
лучше переместить этот код на 20 строку

2023-01-22 10:39 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  display: flex;
разный формат написания стилей.
в этом коде ты используешь js templates. Используй лучще общий подход

```

export const PreviewHeader = styled("div")({
  margin: "",
});
```

2023-01-22 10:40 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  width: "1120px",
для чего хардкод

2023-01-22 10:40 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  image: string;
лучше imageUrl

2023-01-22 10:40 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  width: " 1120px",
ненужных хардкод

2023-01-22 10:40 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  width: "1120px",
хардкод

2023-01-22 10:41 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  width: "220px",
почему 220px?

2023-01-22 10:43 UTC, dmowski commented on app/src/features/ShowCaseEditor/hooks/showcaseEditor/showcaseEditorContext.tsx
> +      categories: [],
а почему появились категории?
может это тэги?

2023-01-22 10:53 UTC, MishaMgla commented on app/src/assets/styles/globals.css
> +  --color-neutral-7: #fff;
На этом макете да, 9,7,10 стали fff. Может это отдельной задачей сделать маппинг light, dark всех переменных цветов?

2023-01-22 10:55 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +type PreviewHeaderProps = {
есть

2023-01-22 10:56 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/PreviewContent.tsx
> +            {data.roles
Не понял синтаксис. Сделать проверку, что есть доп роль?

2023-01-22 11:04 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  width: "220px",
это ширина самого большого блока названия категории в макете

2023-01-22 11:05 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/hooks/showcaseEditor/showcaseEditorContext.tsx
> +      categories: [],
я перепутал, переименовал

2023-01-22 11:57 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  display: flex;
сделал

2023-01-22 11:59 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  image: string;
поправил

2023-01-22 12:17 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  width: "1120px",
сделал

2023-01-22 19:10 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ActivitiesForm/ActivitiesForm.stories.tsx
> +      tags: [],
добавить нужно в 
common/database-structure.txt

2023-01-22 19:32 UTC, dmowski requested changes

2023-01-22 19:32 UTC, dmowski commented on app/src/assets/styles/globals.css
> +  --color-neutral-7: #fff;
https://trello.com/c/IAZ5t8sx/261-%D0%B2%D0%BD%D0%B5%D1%81%D1%82%D0%B8-%D1%86%D0%B2%D0%B5%D1%82%D0%BA%D0%B0-%D1%82%D0%B5%D0%BC%D0%BD%D0%B0%D1%8F-%D1%82%D0%B5%D0%BC%D0%B0-%D0%B2-%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2%D1%83%D1%8E-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%83

2023-01-22 19:32 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/ViewContent.tsx
> +export function ViewContent(): JSX.Element {
Нужно изменить название папки

2023-01-22 19:32 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/ViewContent.tsx
> +        <Wrapper>
Может переименовать в ContentContainer

2023-01-22 19:32 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  width: "1120px",
думаю стоит сделать maxWidth

2023-01-22 19:32 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +export const InfoWrapper = styled("div")({
export const InfoWrapper = styled("div")({
  display: "grid",
  gap: "44px",
  gridTemplateColumns: "200px 2fr",
});

2023-01-22 19:32 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +export const CategoryContainer = styled("div")({
TagsContainer

2023-01-22 19:32 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +export const Category = styled(CardCategory)({
Tag

2023-01-22 19:32 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +export const InfoWrapper = styled("div")({
rename to
export const InfoRow = styled("div")({

2023-01-22 19:32 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/PreviewContent.tsx
> +            {data.roles
у тебя код такой
```
{data.roles
                  .map((role, index) => {
                    if (index > 0) {
                      return role.name;
                    }
                  })
                  .filter(Boolean)
                  .join(", ")}
```

все эти строчки и массивы можно заменить одной строкой.
`<InfoDetails>{data.roles?.[0].name}</InfoDetails>`

2023-01-22 19:32 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcasePreview/style.tsx
> +  width: "840px",
нужно убрать хардкод

2023-01-24 13:08 UTC, dmowski approved these changes

2023-01-25 13:33 UTC, merged