[UI Component]: ShowcaseCard
profolio-team/customer-admin pull request #356
Opened 2023-02-02 19:22 UTC by deq406

## Описание 📝
Сделал верстку карточки для шоукейса вопрос по галочке, которая выглядит криво

Ссылка на фигму:

https://www.figma.com/file/KLY9iLydGyTzGPHzyrccvo/ProFolio-Prototype?node-id=11468%3A100550&t=YRGFIdgfVMw7NaY7-0

---

ПР полностью готов к финальному ревью. Нужно проверить всё

---

### Скриншоты экранов если нужны 📺 🖥

![image](https://user-images.githubusercontent.com/55044962/216428773-1d4bdfbd-5bc3-491e-9834-30f53f53200d.png)
Нажали на чекбокс:
![image](https://user-images.githubusercontent.com/55044962/216428938-29a89114-2f4b-4367-9138-997f10b04a80.png)

---

### Чеклист проверки ✅

- [ ] Проверил в мобильной версии
- [ ] Проверил в Firefox
- [ ] Изображения оптимизированы
- [ ] Компоненты в сторибуке не сломались
- [ ] Readme актуальный
- [ ] database-structure.txt актуальный

2023-02-02 19:47 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +}
Нужно расширить API

interface CardProps {
  category: string;
  bottomText: string;
  imageURL: string;
  checked: boolean;
  onToggleCheck: (newValue:boolean) => void
}

2023-02-02 19:47 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +  const [checkState, setCheckState] = useState(false);
checkState брать из пропсов

2023-02-02 19:47 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +    setCheckState(e?.target.checked);
setCheckState брать из пропсов

2023-02-02 19:49 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +        border: `${checkState ? `3px solid ${COLORS["theme-primary"]}` : " "}`,
При переключении изменяется размер компонента и он начинает прыгать
<img width="478" alt="image" src="https://user-images.githubusercontent.com/17089422/216434703-e0328cf6-af61-415f-add8-9ed5d4795077.png">
<img width="517" alt="image" src="https://user-images.githubusercontent.com/17089422/216434753-42021743-12b9-4252-b5b8-37c3804993ec.png">

2023-02-02 19:50 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +            Get in touch
Для чего нужна эта кнопка?

2023-02-02 19:51 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +          <CheckBoxSpan></CheckBoxSpan>
Лучше использовать чекбокс из библиотеки
https://mui.com/material-ui/react-checkbox/

2023-02-02 19:51 UTC, dmowski requested changes
Добавь .DS_Store в gitignore и удали его из пулл реквеста.

2023-02-02 19:52 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +  height: "220px",
лучше не использовать хардкод для обьявления высоты

2023-02-02 19:53 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +  padding: "0.75rem 1.25rem",
почему rem?

2023-02-02 19:53 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +  fontFamily: "Roboto",
зачем переопределять шрифт?

2023-02-02 19:54 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +  fontWeight: "400",
лучше удалить эти свойства

2023-02-02 19:54 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +  /* identical to box height, or 20px */
ненужный коммент

2023-02-02 19:54 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +  fontFamily: "Roboto",
удалить переопределени шрифтов

2023-02-02 19:54 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +  overflow: "hidden",
Зачем это свойство в карточке?

2023-02-02 19:55 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +  fontSize: "1.125rem",
Используй подходящий компонент из типографики
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/17089422/216435943-58cc6110-f56a-4564-94d3-9568fafd6257.png">

2023-02-06 20:07 UTC, dmowski commented
нужно удалить этот файл из ПР
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/17089422/217074046-dd07e932-a8df-47a9-8af8-85be0bce7856.png">

2023-02-06 20:07 UTC, deq406 commented on app/src/components/ShowcaseCard/style.ts
> +  overflow: "hidden",
Для того чтобы текст не выходил за карточку если слишком большой

2023-02-06 20:09 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +          <CheckBoxSpan></CheckBoxSpan>
еще актуально

2023-02-06 22:46 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +      <BottomTextBox>
для чего нужна это кнопка? она же ничего не делает

2023-02-06 22:46 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +          ? `inset 100em 0px rgba(16, 18, 19, 0.4), 0 0 0 3px ${COLORS["theme-primary"]}`
100em почему em?

2023-02-06 23:01 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +export const StyledInput = styled(Checkbox)({
Примеры того как кастомизируются елементы material UI

app/src/components/Input/formLabel.style.ts
app/src/components/Input/input.style.ts
app/src/components/Input/textField.style.ts

2023-02-06 23:02 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +export const StyledInput = styled(Checkbox)({
Я бы сделал отдельный компонент. Назвал бы его WhiteCheckbox в котором будут стили с белым фоном.

2023-02-06 23:03 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +          <Typography variant={"caption"} component={"p"}>
кста, атрибут component можно не писать

2023-02-06 23:04 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +        <StyledInput size="medium" onChange={(e) => onToggleCheck(e?.target.checked)} />
StyledInput - Слово Input сбивает с толку. Лучши использовать Checkbox

2023-02-06 23:04 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +        <StyledInput size="medium" onChange={(e) => onToggleCheck(e?.target.checked)} />
если по умолчанию checked будет true, этот чекбокс будет с галочкой или без галочки?

2023-02-06 23:05 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +        <BottomText variant="body1" component="p">
component можно не использовать

2023-02-06 23:06 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +  lineHeight: "143%",
это точно нужно?

2023-02-07 11:52 UTC, deq406 commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +        <StyledInput size="medium" onChange={(e) => onToggleCheck(e?.target.checked)} />
Сейчас без галочки, сделал чтоб было с галочкой

2023-02-07 11:54 UTC, deq406 commented on app/src/components/ShowcaseCard/style.ts
> +  lineHeight: "143%",
Это для блока с текстом сверху где сейчас написано health & insurance

2023-02-07 12:51 UTC, deq406 commented on app/src/components/ShowcaseCard/style.ts
> +          ? `inset 100em 0px rgba(16, 18, 19, 0.4), 0 0 0 3px ${COLORS["theme-primary"]}`
Не понимаю чем заменить, проценты не работают

2023-02-07 12:56 UTC, deq406 commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +      <BottomTextBox>
BottomTextBox типо как нижний текст карточки, это не Button вроде а mui Box

2023-02-07 17:15 UTC, dmowski commented on app/src/components/ShowcaseCard/ShowcaseCard.tsx
> +      <BottomTextBox>
тогда может лучше переименовать в CardTitle

2023-02-07 17:16 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +          ? `inset 100em 0px rgba(16, 18, 19, 0.4), 0 0 0 3px ${COLORS["theme-primary"]}`
Можешь пикселями зафигачить. Думаю норм будет)

2023-02-07 17:20 UTC, dmowski commented on app/src/components/ShowcaseCard/style.ts
> +export const StyledInput = styled(Checkbox)({
Я бы сделал такой компонент 

<img width="188" alt="image" src="https://user-images.githubusercontent.com/17089422/217316846-4798ce3b-3044-4f47-9bff-51c31bbed08c.png">

app/src/components/Checkbox/WhiteBgCheckbox.ts

с таким api
interface WhiteBgCheckboxProps {
  checked: boolean;
  setNewValue: (newState: boolean) => boid
}



и его использовал бы в твоем компоненте
[app/src/components/ShowcaseCard/](https://github.com/profolio-team/customer-admin/pull/356/files/07d75510520f8204ec90d91b34e24e1be1d42392#diff-9d5b48436a6ca46733132b2b85bf846fbdcd8fb3d7ab4f9b4b1fed03b784a749)

2023-02-07 19:34 UTC, dmowski approved these changes

2023-02-07 19:47 UTC, merged