[BUG]: Pop-up after clicking the "Save & Preview Showcase
profolio-team/customer-admin pull request #441
Opened 2023-04-03 01:55 UTC by Bolshoff

## Описание 📝

Если юзер не заполнил все описания всех активностей на 3-м шаге создания шоукейса, то при нажатии на кнопку “Save & Preview Showcase” ему должен выдаваться попап

---

### Чеклист проверки ✅

- [ ] Проверил в мобильной версии
- [ ] Проверил в Firefox
- [ ] Изображения оптимизированы
- [ ] Компоненты в сторибуке не сломались
- [ ] Readme актуальный
- [ ] database-structure.txt актуальный

2023-04-03 21:09 UTC, dmowski requested changes

2023-04-15 15:38 UTC, Diminich commented on app/src/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.stories.tsx
>  const contentJSX: JSX.Element = (
Стоит ли перенести сразу этот JSX в компоненту, а не прокидывать как функцию?

2023-04-15 15:41 UTC, Diminich commented on app/src/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.stories.tsx
> +);
Стоит ли прокидывать эту функцию через пропсы или стоит сразу JSX прописать в компоненте?

2023-04-15 15:47 UTC, Diminich commented on app/src/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +            <Box sx={{ display: "flex", alignItems: "center", gap: "1rem" }}>
Стоит ли content оборачивать в Box?

2023-04-16 21:25 UTC, dmowski commented on app/src/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +export default function ShowcaseUnfilledModal({
всё еще актуально

2023-04-16 21:26 UTC, dmowski commented on app/src/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +            <Box sx={{ display: "flex", alignItems: "center", gap: "1rem" }}>
как сам думаешь?

2023-04-16 21:26 UTC, dmowski commented on app/src/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.stories.tsx
> +);
какие плюсы и минусы каждого подхода?

2023-04-16 21:28 UTC, dmowski commented on app/src/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +      onClose={handleClose}
onClose={() => {
  onCancel(false);
}}

в чем был смысл выносить вызов одной функции в новую функцию handleClose?

2023-04-16 21:29 UTC, dmowski commented on app/src/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +              <Button variant={"outlined"} onClick={onPreview}>
onClick={()=> togglePreview(true)}

2023-04-16 21:30 UTC, dmowski commented on app/src/components/ShowcaseUnfilledModal/style.ts
> +export const ModalFullBox = styled.div({
для чего нужен этот компонент?

2023-04-17 20:34 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/Conclusion/Conclusion.tsx
> +  const isReadyForConclusion = isValidStep(2);
думаю стоит переименовать переменную в что-то более по смыслу подходящее.

isReadyForConclusion - как будто говорит что готовы к конклюжену. Хотя мы уже на странице конклюжена

Лучше переименовать в isFilledContent

2023-04-17 20:36 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.stories.tsx
> +  unfilledActivites: ShowcaseData;
Activities
опечатка. Установи плагин "Code Spell Checker" - чтобы проверять правописание в коде

2023-04-17 20:38 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.stories.tsx
> +      unfilledActivites={data}
лучше переименовать unfilledActivites -> showcaseData

unfilledActivites - больше похоже на массив чегото. Хотя компонент принимает весь шоукейс

2023-04-17 20:43 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/style.ts
> +  width: "480px",
лучше сделать верстку адаптивной
maxWidth: "480px",
так оно лучше будет смотреться на маленьких экранах

2023-04-17 20:44 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +        <Box sx={{ display: "flex", flexDirection: "column", gap: "1rem", padding: "2rem" }}>
rem лучше использовать для расстояний которые зависят от шрифта.
Тут лучше использовать пиксели

2023-04-17 20:44 UTC, dmowski commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +            <Box sx={{ display: "flex", alignItems: "center", gap: "1rem" }}>
gap: "10px"

2023-04-20 17:56 UTC, dmowski commented
Баг. У меня "Software Developer | Main" заполненны. а  Web Developer нет

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/17089422/233448791-dd7f1159-25f5-4920-b1a9-a6093db5ebb8.png">

2023-04-21 20:01 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.stories.tsx
> +} as Meta;
Это метаданные? А где они отображаются?

2023-04-21 20:07 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.stories.tsx
> +  name: "111",
Думаю лучше использовать более реальные, или очевидные данные. Утрированно, в данном случае, например, если, там где должно быть значение name отобразятся данные conclusion - 1111, то это сложно заметить. В папке ShowCaseEditor в сторибуках много заполненных

2023-04-21 20:32 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +import { Modal, Box } from "@mui/material";
Можно объединить с импортом выше

2023-04-21 20:52 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +                  .filter(({ activities }) => activities.length > 0 && activities)
а что проверяет второе условие "&& activities" ?

2023-04-21 21:13 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +                    activities.map(({ description }) => {
мне кажется где-то здесь должен быть переход к activity. Можно попробовать console.log для description, посмотреть правильные ли данные попадают в условие

2023-04-21 21:16 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +                    {isUnfilledActivities && (
Может создастся пустой ListItem?

2023-04-21 21:22 UTC, MishaMgla commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +            {cancelButtonTitle && (
А что здесь происходит, какая связь названия кнопки cancel с кнопкой confirm?

2023-04-21 21:26 UTC, Diminich commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +                  .filter(({ activities }) => activities.length > 0 && activities)
Лишнее. Хз зачем написал, уберу)

2023-04-21 21:27 UTC, Diminich commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +                    activities.map(({ description }) => {
Не понял тут чуток

2023-04-21 21:28 UTC, Diminich commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +                    {isUnfilledActivities && (
Нет. Если он пустой, значит все активности заполнены и модалка просто не откроется

2023-04-21 21:29 UTC, Diminich commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +            {cancelButtonTitle && (
Что за кнопка confirm? Не понял

2023-04-21 21:33 UTC, Diminich commented on app/src/features/ShowCaseEditor/components/ShowcaseUnfilledModal/ShowcaseUnfilledModal.tsx
> +            {cancelButtonTitle && (
Глянул. Хз, не я это писал. Гляну позже)

2023-04-22 01:43 UTC, dmowski approved these changes

2023-04-22 01:44 UTC, merged