Add 404 error page
profolio-team/customer-admin pull request #96
Opened 2022-04-19 16:38 UTC by Anton-Shvetc

add 404 error page

2022-04-19 18:02 UTC, dllsc commented on app/src/views/Error/NotFoundPage.tsx
> +              {'m.jones@companyname.com"'}
думаб mail можно вынести в переменную, потом он поменяется, а используется в нескольких местах

2022-04-19 21:50 UTC, dmowski requested changes

2022-04-19 21:50 UTC, dmowski commented on app/src/components/Error/ErrorPage.tsx
> +      sx={{
лучше вынести стили в файл
app/src/components/Error/style.ts

2022-04-19 21:50 UTC, dmowski commented on app/src/components/Error/ErrorPage.tsx
> +      sx={{
по возможности лучше не писать стили в разметке

2022-04-19 21:50 UTC, dmowski commented on app/src/components/Error/ErrorPage.tsx
> +  const ADMINISTRATOR_EMAIL = "m.jones@companyname.com";
лучше вынести эти переменные в конфиг
app/src/hooks/config.tsx

2022-04-21 23:01 UTC, dmowski requested changes
Почти идеально. 
Небольшие замечания, вопросы

2022-04-21 23:01 UTC, dmowski commented on app/src/components/ErrorPage/ErrorPage.tsx
> +          {500 <= Number(code) && (
Можешь описать для чего такое условие? (немного непонятно мне)

2022-04-27 22:51 UTC, merged